---
- hosts: all
  become: yes

  vars:
    username: "student"
    hostname: "programare-vm-lite"

  tasks:
  - name: Basic setup
    include: basic.yml

  - name: Reboot the machine
    reboot:

  - name: Dev-tools setup
    include: ../playbooks-common/dev-tools.yml

  - name: Dev-tools setup
    include: dev-tools.yml
